spring:
  application:
    name: IMS_Team4
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ims?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

# Protect cookies from csrf and xss
server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: strict

