spring:
  application:
    name: IMS_Team4
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:sqlserver://LAPTOP-H0L0INL8\SQLEXPRESS:1433;databaseName=TestDB;encrypt=false;
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        hbm2ddl:
          auto: update
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html